### ISSUE TITLE
Change Interface names back to eth0 and eth1

### ISSUE THREAD

**Issue by Jnull** [sudomesh/exitnode#22]
The following links are the process to change default network interface names back to eth0 and eth1

https://www.itzgeek.com/how-tos/mini-howtos/change-default-network-name-ens33-to-old-eth0-on-ubuntu-16-04.html

https://netplan.io/examples

Note netplan needs option=true on management network ports or Network Wait service will run for a realllly long time and cable will need to be physically pulled and plugged in again to boot.

**Comment by bennlich** [comment]
Hey @Jnull I think this documentation info should go in the trello, not exitnode issues. Can you move it here: https://trello.com/c/JdHnOzeS/1-fix-the-he-exit-node ?

**Comment by Jnull** [comment]
@bennlich, I'm not sure what this has to do with trello, as trello seems to be more high level updates and progress not technical issues.  I'll just close it.

**Comment by bennlich** [comment]
I've been using trello to keep track of some of the work done in preparing the HE server, so I think these links would not be out of place there. If I were my future self looking for information about some of the decisions we made when configuring the machine we end up deploying to HE, that is probably where I would look.

**Comment by bennlich** [comment]
I think I understand what you're going for here though--this is the repo you would look in the next time you're going to set up an exitnode.

**Comment by Jnull** [comment]
Also reading, why interfaces were changed from ex: eth0 to enp3s0, etc..
