### ISSUE TITLE
tunneldigger picks next available interface in l2tp_broker.cfg

### ISSUE THREAD

**Issue by Jnull** [sudomesh/exitnode#23]
Apparently when the assigned interface in /opt/tunneldigger/broker/l2tp_broker.cfg is removed from the system, tunneldigger picks the next interface the system has access too. In this case "eth0" should have been the interface, but "lo" was assigned.

**Comment by bennlich** [comment]
Hey @Jnull not sure I follow. Can you list the steps to reproduce, and maybe include some logs? :)

**Comment by Jnull** [comment]
yesterday i double check the tunnel again (replaced all ips for omni's) and found it wasn't working. 

i checked /opt/tunneldigger/broker/l2tp_broker.cfg  and found that interface=lo - i changed it back to  interface=eth0 and now the tunnel works again.  

we never changed /opt/tunneldigger/broker/l2tp_broker.cfg  interface= so something happened.
