### ISSUE TITLE
Can we separate out the walled garden?

### ISSUE THREAD

**Issue by max-b** [sudomesh/exitnode#4]
@stillson is probably the person to answer this, but I'm wondering if we can separate the walled garden out into it's own package. I guess ideally it would be a debian package, but if that's too much work, it could have its own installer. Mostly I just think we should try to move it into it's own repo.

I think there are probably a lot of folks interested in a solution like this, so we should allow folks to integrate them without having to separate it from our entire exitnode provision setup.

**Comment by stillson** [comment]
I would be totally up for turning this into a package, debian or otherwise.
It's pretty straightforward to do.

C

Chris

**Comment by max-b** [comment]
Awesome - maybe I could help out/watch you do that. I've never packaged anything for Debian before and would definitely be interested in best practices, etc.

**Comment by stillson** [comment]
I've never packaged for debian. I have packaged for a bunch of other
systems, so I expect it to be pretty straight forward.

I'll keep you updated.

C

Chris

**Comment by paidforby** [comment]
walled garden was abandoned
