### ISSUE TITLE
Tunnel broker logs go nowhere

### ISSUE THREAD

**Issue by bennlich** [sudomesh/exitnode#9]
@gobengo @jhpoelen 

It looks like the tunneldigger broker logs currently go nowhere. This is because the `[log]` config in `/opt/tunneldigger/broker/l2tp_broker.cfg` is not actually used anywhere by the broker script (apparently this config was [deprecated in v2 of tunneldigger](https://github.com/wlanslovenija/tunneldigger/blob/master/HISTORY.rst#v020-2015-dec-24)), and because `/etc/init.d/tunneldigger` does not send the output of `start-stop-daemon` anywhere.

I think the quickest fix would be something like this: https://stackoverflow.com/a/21029952

**Comment by jhpoelen** [comment]
note that when switching over to systemd service ; tunneldigger logs appear nicely when running ```sudo journalctl -u tunneldigger``` - 

```
# journalctl -u tunneldigger
-- Logs begin at Tue 2018-03-13 23:28:13 UTC, end at Tue 2018-03-13 23:28:58 UTC. --
Mar 13 23:28:17 ubuntu-s-1vcpu-1gb-fra1-01 systemd[1]: Started tunneldigger tunnelling network daemon using l2tpv3.
Mar 13 23:28:18 ubuntu-s-1vcpu-1gb-fra1-01 python[1338]: [INFO/tunneldigger.broker] Initializing the tunneldigger broker.
Mar 13 23:28:18 ubuntu-s-1vcpu-1gb-fra1-01 python[1338]: [INFO/tunneldigger.broker] Registered script '/opt/tunneldigger/bro
Mar 13 23:28:18 ubuntu-s-1vcpu-1gb-fra1-01 python[1338]: [INFO/tunneldigger.broker] Registered script '/opt/tunneldigger/bro
Mar 13 23:28:18 ubuntu-s-1vcpu-1gb-fra1-01 python[1338]: [INFO/tunneldigger.broker] Maximum number of tunnels is 1024.
Mar 13 23:28:18 ubuntu-s-1vcpu-1gb-fra1-01 python[1338]: [INFO/tunneldigger.broker] Tunnel identifier base is 100.
Mar 13 23:28:18 ubuntu-s-1vcpu-1gb-fra1-01 python[1338]: [INFO/tunneldigger.broker] Tunnel port base is 20000.
Mar 13 23:28:18 ubuntu-s-1vcpu-1gb-fra1-01 python[1338]: [INFO/tunneldigger.broker] Namespace is experiments.
Mar 13 23:28:18 ubuntu-s-1vcpu-1gb-fra1-01 python[1338]: [INFO/tunneldigger.broker] Listening on [some ip]:8942.
Mar 13 23:28:18 ubuntu-s-1vcpu-1gb-fra1-01 python[1338]: [INFO/tunneldigger.broker] Broker initialized.
````

also, see https://github.com/wlanslovenija/tunneldigger/blob/master/broker/contrib/tunneldigger.service .

@bennlich seems like this approach is much simpler than the init.d script hacking. do you think this resolves the issue?

**Comment by jhpoelen** [comment]
@yardenac @juul - fyi I've replaced init.d tunneldigger with systemd tunnel digger (see above) to exit.sudo node to help troubleshoot https://github.com/sudomesh/bugs/issues/8 . Please holler if you have concerns.

**Comment by bennlich** [comment]
Yes--seems good to me. Nice find. Linking to your commit for posterity: https://github.com/sudomesh/exitnode/commit/f47ae194efc2f14a061ffdeed123e3e8da154f2e. Did you forget to add the .service file in that commit?

Any idea why they have both a .service and a .upstart file in the wlanslovenija repo?

**Comment by jhpoelen** [comment]
@bennlich note quite sure why both .service and .upstart files exist. Perhaps to support systems that do not have systemd. @mitar might now.
